// RAÇAS D&D 5e (71) — base do menu de criação. Gerado da planilha do Moon.
// Mesma fonte do servidor (game/races.py). Não editar à mão.
const RACES = [
 {
  "id": "anao_anao_da_colina",
  "name_pt": "Anão",
  "name_en": "Dwarf",
  "subrace": "Anão da Colina",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "CON": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 SAB",
  "size": "Médio",
  "speed": "7,5 m (sem penalidade por armadura pesada)",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Anão",
  "traits": "Resiliência Anã (vantagem em testes contra veneno, resistência a dano de veneno); Treino Anão em Combate (machado de batalha, machadinha, martelo leve, martelo de guerra); Proficiência com Ferramentas (artesão de ferreiro, cervejeiro ou pedreiro); Conhecimento de Pedra; Robustez Anã (+1 PV por nível)",
  "desc": "Anões resistentes e tradicionalistas, ligados à pedra e à forja. A linhagem da colina dá mais resistência física e sabedoria — clássica para clérigos e bárbaros.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": true,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "anao_anao_da_montanha",
  "name_pt": "Anão",
  "name_en": "Dwarf",
  "subrace": "Anão da Montanha",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "CON": 2,
   "FOR": 2
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +2 FOR",
  "size": "Médio",
  "speed": "7,5 m (sem penalidade por armadura pesada)",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Anão",
  "traits": "Resiliência Anã; Treino Anão em Combate; Proficiência com Ferramentas; Conhecimento de Pedra; Treino Anão com Armaduras (proficiência com armaduras leves e médias)",
  "desc": "Anões das alturas, mais fortes e marciais. O único 'sub-raça' que dá +2 e +2 em atributos, ótimo para guerreiros e paladinos em armadura.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": true,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "elfo_alto_elfo",
  "name_pt": "Elfo",
  "name_en": "Elf",
  "subrace": "Alto Elfo",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "DES": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Élfico, +1 idioma",
  "traits": "Sentidos Aguçados (proficiência em Percepção); Ancestralidade Feérica (vantagem contra encantamento, imune a sono mágico); Transe (medita 4h em vez de dormir 8h); Treino Élfico com Armas (espada longa, espada curta, arco curto, arco longo); Truque (um truque de mago, usa INT)",
  "desc": "O elfo arcano e erudito. O truque de mago grátis e o bônus de Inteligência fazem dele excelente para magos e arcanos em geral.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "elfo_elfo_da_floresta",
  "name_pt": "Elfo",
  "name_en": "Elf",
  "subrace": "Elfo da Floresta",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "DES": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 SAB",
  "size": "Médio",
  "speed": "10,5 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Élfico",
  "traits": "Sentidos Aguçados; Ancestralidade Feérica; Transe; Treino Élfico com Armas; Pés Ligeiros (deslocamento 10,5 m); Máscara da Natureza (pode se esconder mesmo levemente obscurecido por fenômenos naturais)",
  "desc": "Caçadores e guardiões das matas. Velocidade extra e camuflagem natural — perfeito para patrulheiros e druidas furtivos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "elfo_elfo_negro_drow",
  "name_pt": "Elfo",
  "name_en": "Elf",
  "subrace": "Elfo Negro (Drow)",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "DES": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CAR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro Superior 36 m",
  "languages": "Comum, Élfico",
  "traits": "Sentidos Aguçados; Ancestralidade Feérica; Transe; Sensibilidade à Luz Solar (desvantagem em ataques e Percepção visual sob luz solar direta); Magia Drow (luzes dançantes; fogo das fadas no 3º nível; escuridão no 5º; usa CAR); Treino Drow com Armas (rapieira, espada curta, besta de mão)",
  "desc": "Elfos das profundezas do Subterrâneo. Visão no escuro lendária e magia inata; a sensibilidade à luz é o preço. Ótimos para bardos e feiticeiros.",
  "appearance": {
   "size": "medium",
   "skin": "#6a5b78",
   "hair": "#e8e2ea",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "halfling_pes_leves",
  "name_pt": "Halfling",
  "name_en": "Halfling",
  "subrace": "Pés-Leves",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "DES": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CAR",
  "size": "Pequeno",
  "speed": "7,5 m",
  "darkvision": "—",
  "languages": "Comum, Halfling",
  "traits": "Sortudo (rerrola 1 natural em ataque, teste ou resistência); Bravura (vantagem contra amedrontado); Agilidade Halfling (move-se pelo espaço de criaturas maiores); Furtividade Natural (pode se esconder atrás de criaturas maiores)",
  "desc": "Os pequenos mais carismáticos e discretos. Combinam sorte, coragem e furtividade — clássicos para ladinos e bardos.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "halfling_robusto",
  "name_pt": "Halfling",
  "name_en": "Halfling",
  "subrace": "Robusto",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "DES": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CON",
  "size": "Pequeno",
  "speed": "7,5 m",
  "darkvision": "—",
  "languages": "Comum, Halfling",
  "traits": "Sortudo; Bravura; Agilidade Halfling; Resiliência Robusta (vantagem contra veneno, resistência a dano de veneno)",
  "desc": "Linhagem halfling mais durável, com sangue anão na ascendência. A resistência a veneno os torna sobreviventes natos.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "humano_padrao",
  "name_pt": "Humano",
  "name_en": "Human",
  "subrace": "Padrão",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "FOR": 1,
   "DES": 1,
   "CON": 1,
   "INT": 1,
   "SAB": 1,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+1 em todos os atributos",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, +1 idioma",
  "traits": "Versatilidade pura: bônus em cada atributo, sem traços especiais",
  "desc": "A raça mais adaptável e ambiciosa. A versão padrão espalha pontos por tudo — boa quando você quer flexibilidade total.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "humano_variante",
  "name_pt": "Humano",
  "name_en": "Human",
  "subrace": "Variante",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {},
  "bonus_flex": "+1 em dois atributos à escolha",
  "bonus_text": "+1 em dois atributos à escolha",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, +1 idioma",
  "traits": "Proficiência em uma perícia à escolha; um talento à escolha já no 1º nível",
  "desc": "A escolha de quem quer otimizar: um talento logo de cara abre builds poderosas desde o nível 1. Uma das raças mais fortes para min-maxing.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "draconato",
  "name_pt": "Draconato",
  "name_en": "Dragonborn",
  "subrace": null,
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "FOR": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 CAR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Dracônico",
  "traits": "Ascendência Dracônica (escolhe um tipo de dragão → define o tipo de dano e o formato do sopro); Arma de Sopro (sopro em cone ou linha, resistência por save, escala com o nível); Resistência a Dano (do tipo da sua ascendência)",
  "desc": "Descendentes de dragões, orgulhosos e marciais. O sopro elemental e a resistência refletem a linhagem — fortes para paladinos e guerreiros.",
  "appearance": {
   "size": "medium",
   "skin": "#7a9a5a",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "draconic",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "gnomo_gnomo_da_floresta",
  "name_pt": "Gnomo",
  "name_en": "Gnome",
  "subrace": "Gnomo da Floresta",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "INT": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 INT, +1 DES",
  "size": "Pequeno",
  "speed": "7,5 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Gnômico",
  "traits": "Esperteza Gnômica (vantagem em saves de INT, SAB e CAR contra magia); Ilusionista Natural (truque ilusão menor); Conversar com Pequenos Animais",
  "desc": "Gnomos travessos e ligados à natureza, com um dom para ilusões. A esperteza contra magia é uma das melhores defesas raciais do jogo.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "gnomo_gnomo_das_rochas",
  "name_pt": "Gnomo",
  "name_en": "Gnome",
  "subrace": "Gnomo das Rochas",
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "INT": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 INT, +1 CON",
  "size": "Pequeno",
  "speed": "7,5 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Gnômico",
  "traits": "Esperteza Gnômica; Conhecimento de Artífice (bônus em História sobre itens mágicos/tecnológicos); Engenhoqueiro (cria pequenos dispositivos mecânicos)",
  "desc": "Inventores e engenhocas natos. A linhagem mais resistente e curiosa — combina perfeitamente com artífices e magos.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "gnomo_gnomo_das_profundezas_svirfneblin",
  "name_pt": "Gnomo",
  "name_en": "Gnome",
  "subrace": "Gnomo das Profundezas (Svirfneblin)",
  "source": "Elemental Evil / Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "INT": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 INT, +1 DES",
  "size": "Pequeno",
  "speed": "7,5 m",
  "darkvision": "Visão no Escuro Superior 36 m",
  "languages": "Comum, Gnômico, Subcomum",
  "traits": "Esperteza Gnômica; Camuflagem de Pedra (vantagem em Furtividade em terreno rochoso)",
  "desc": "Gnomos do Subterrâneo profundo, cinzentos e furtivos. Visão no escuro superior e camuflagem natural fazem deles exploradores ideais das cavernas.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "meio_elfo",
  "name_pt": "Meio-Elfo",
  "name_en": "Half-Elf",
  "subrace": null,
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "CAR": 2
  },
  "bonus_flex": "+2 CAR, +1 em dois outros à escolha",
  "bonus_text": "+2 CAR, +1 em dois outros à escolha",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Élfico, +1 idioma",
  "traits": "Ancestralidade Feérica (vantagem contra encantamento, imune a sono mágico); Versatilidade em Perícias (proficiência em duas perícias à escolha)",
  "desc": "O melhor de dois mundos: carisma alto, flexibilidade de atributos e duas perícias livres. Uma das raças mais versáteis e populares para qualquer classe baseada em CAR.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "meio_orc",
  "name_pt": "Meio-Orc",
  "name_en": "Half-Orc",
  "subrace": null,
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "FOR": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 CON",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Orc",
  "traits": "Ameaçador (proficiência em Intimidação); Resistência Implacável (ao cair a 0 PV, fica com 1 PV em vez disso — 1x por descanso longo); Ataques Selvagens (ao acertar um crítico corpo a corpo, rola um dado de dano extra)",
  "desc": "Brutos resistentes, ideais para a linha de frente. Resistência Implacável os mantém de pé quando deveriam cair — sonho de qualquer bárbaro.",
  "appearance": {
   "size": "medium",
   "skin": "#7a8a5a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": "tusks"
  }
 },
 {
  "id": "tiefling",
  "name_pt": "Tiefling",
  "name_en": "Tiefling",
  "subrace": null,
  "source": "Player's Handbook (2014)",
  "tier": "nucleo",
  "tier_color": "#3fae5a",
  "availability": "Núcleo (PHB)",
  "bonus": {
   "CAR": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CAR, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Infernal",
  "traits": "Resistência Infernal (resistência a dano de fogo); Legado Infernal (taumaturgia; repreensão infernal no 3º nível; escuridão no 5º; usa CAR)",
  "desc": "Descendentes de pactos infernais, marcados por chifres e cauda. Resistência a fogo e magia inata os tornam feiticeiros e bruxos natos.",
  "appearance": {
   "size": "medium",
   "skin": "#a85a5a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "curved",
   "wings": "none",
   "tail": "devil",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "aarakocra",
  "name_pt": "Aarakocra",
  "name_en": "Aarakocra",
  "subrace": null,
  "source": "Elemental Evil Player's Companion",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "DES": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 SAB",
  "size": "Médio",
  "speed": "7,5 m, voo 15 m",
  "darkvision": "—",
  "languages": "Comum, Aarakocra, Áurico",
  "traits": "Voo (não pode usar armadura média/pesada para voar); Garras (ataque natural)",
  "desc": "Homens-pássaro do Plano do Ar. Voo no nível 1 é poderosíssimo — muitas mesas restringem por isso. Excelente para exploradores e arqueiros.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "feather",
   "tail": "none",
   "head": "avian",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "genasi_genasi_do_ar",
  "name_pt": "Genasi",
  "name_en": "Genasi",
  "subrace": "Genasi do Ar",
  "source": "Elemental Evil Player's Companion",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CON": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 DES",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Primordial",
  "traits": "Respiração Infinita (segura o fôlego indefinidamente); Misturar-se ao Vento (lança levitar no 3º nível, 1x por descanso longo)",
  "desc": "Tocados pelo Plano do Ar, ágeis e leves. A linhagem aérea favorece mobilidade e magia de movimento.",
  "appearance": {
   "size": "medium",
   "skin": "#bcd6e0",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "genasi_genasi_da_terra",
  "name_pt": "Genasi",
  "name_en": "Genasi",
  "subrace": "Genasi da Terra",
  "source": "Elemental Evil Player's Companion",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CON": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 FOR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Primordial",
  "traits": "Caminhada na Terra (move-se por terreno difícil de origem terrosa sem custo extra); Fundir-se à Pedra (lança passos sem rastro no 3º nível, 1x por descanso longo)",
  "desc": "Genasi sólidos e estáveis, ligados à rocha. Resistentes e furtivos em terreno acidentado.",
  "appearance": {
   "size": "medium",
   "skin": "#9a8466",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "genasi_genasi_do_fogo",
  "name_pt": "Genasi",
  "name_en": "Genasi",
  "subrace": "Genasi do Fogo",
  "source": "Elemental Evil Player's Companion",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CON": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Primordial",
  "traits": "Resistência a fogo; Alcançar a Chama (truque produzir chamas; lança mãos flamejantes no 3º nível, 1x por descanso longo)",
  "desc": "Genasi de temperamento ardente, com visão no escuro e magia de fogo inata. Ótimos para conjuradores ofensivos.",
  "appearance": {
   "size": "medium",
   "skin": "#c8553a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "genasi_genasi_da_agua",
  "name_pt": "Genasi",
  "name_en": "Genasi",
  "subrace": "Genasi da Água",
  "source": "Elemental Evil Player's Companion",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CON": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 SAB",
  "size": "Médio",
  "speed": "9 m, natação 9 m",
  "darkvision": "—",
  "languages": "Comum, Primordial",
  "traits": "Resistência a ácido; Anfíbio (respira ar e água); Alcançar a Onda (truque moldar água; lança criar ou destruir água no 3º nível, 1x por descanso longo)",
  "desc": "Genasi fluidos e adaptáveis, anfíbios de nascença. A linhagem aquática brilha em campanhas marítimas e do Subterrâneo.",
  "appearance": {
   "size": "medium",
   "skin": "#5aa6a6",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "aasimar_protetor",
  "name_pt": "Aasimar",
  "name_en": "Aasimar",
  "subrace": "Protetor",
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CAR": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CAR, +1 SAB",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Celestial",
  "traits": "Resistência Celestial (resistência a dano necrótico e radiante); Mãos Curadoras (cura PV iguais ao seu nível, 1x por descanso longo); Portador de Luz (truque luz); Alma Radiante (no 3º nível: asas de luz, voo e dano radiante extra por 1 min)",
  "desc": "Tocados pelos céus, agentes do bem. A linhagem protetora ganha asas e poder radiante — paladinos e clérigos angelicais ideais.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "feather",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": true,
   "extra": null
  }
 },
 {
  "id": "aasimar_flagelo",
  "name_pt": "Aasimar",
  "name_en": "Aasimar",
  "subrace": "Flagelo",
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CAR": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CAR, +1 CON",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Celestial",
  "traits": "Resistência Celestial; Mãos Curadoras; Portador de Luz; Consumição Radiante (no 3º nível: aura de luz que causa dano radiante a quem estiver perto)",
  "desc": "Aasimar cuja luz interior queima até a si mesmo. A aura de dano constante recompensa quem fica na linha de frente.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": true,
   "extra": null
  }
 },
 {
  "id": "aasimar_caido",
  "name_pt": "Aasimar",
  "name_en": "Aasimar",
  "subrace": "Caído",
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CAR": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CAR, +1 FOR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Celestial",
  "traits": "Resistência Celestial; Mãos Curadoras; Portador de Luz; Mortalha Necrótica (no 3º nível: asas espectrais, amedronta inimigos próximos e causa dano necrótico extra)",
  "desc": "Aasimar que se afastou da luz, sombrio e temível. Tema perfeito para personagens atormentados ou caídos em desgraça.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": true,
   "extra": null
  }
 },
 {
  "id": "firbolg",
  "name_pt": "Firbolg",
  "name_en": "Firbolg",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "SAB": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 SAB, +1 FOR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Élfico, Gigante",
  "traits": "Magia Firbolg (detectar magia e disfarçar-se, 1x cada por descanso curto/longo); Passo Oculto (fica invisível como ação bônus, 1x por descanso); Constituição Poderosa (conta como uma categoria maior para carga); Fala das Bestas e Folhas (comunicação limitada com animais e plantas)",
  "desc": "Gigantes-fada gentis e reclusos, guardiões da floresta. Magia inata e invisibilidade fazem deles druidas e clérigos da natureza excelentes.",
  "appearance": {
   "size": "medium",
   "skin": "#9aa39a",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "golias",
  "name_pt": "Golias",
  "name_en": "Goliath",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "FOR": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 CON",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Gigante",
  "traits": "Atleta Nato (proficiência em Atletismo); Resistência da Pedra (reduz dano com 1d12+CON, 1x por descanso curto); Constituição Poderosa; Nascido na Montanha (resistência a frio, adaptado a grandes altitudes)",
  "desc": "Colossos das montanhas, competitivos e estoicos. Força bruta com mitigação de dano embutida — bárbaros e guerreiros tanques de primeira.",
  "appearance": {
   "size": "medium",
   "skin": "#9aa39a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "kenku",
  "name_pt": "Kenku",
  "name_en": "Kenku",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "DES": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 SAB",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Áurico (entende, mas só fala por imitação)",
  "traits": "Falsificação Perita (vantagem para copiar escrita e objetos); Treino Kenku (proficiência em duas perícias à escolha); Imitação (reproduz sons e vozes que já ouviu)",
  "desc": "Corvídeos amaldiçoados sem voz própria, falam só copiando sons. Falsificadores e espiões natos — ladinos furtivos com um toque trágico.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "avian",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "povo_lagarto",
  "name_pt": "Povo Lagarto",
  "name_en": "Lizardfolk",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CON": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 SAB",
  "size": "Médio",
  "speed": "9 m, natação 9 m",
  "darkvision": "—",
  "languages": "Comum, Dracônico",
  "traits": "Mordida (ataque natural); Artesão Astuto (cria itens com restos de criaturas); Prender o Fôlego (até 15 min); Conhecimento de Caçador (proficiência em duas perícias à escolha); Armadura Natural (CA 13+DES); Mandíbulas Famintas (ação bônus de mordida com PV temporários)",
  "desc": "Répteis pragmáticos de lógica fria e alienígena. Armadura natural e resistência os tornam sobreviventes implacáveis — ótimos bárbaros e druidas.",
  "appearance": {
   "size": "medium",
   "skin": "#6f8f5a",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "reptile",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "tabaxi",
  "name_pt": "Tabaxi",
  "name_en": "Tabaxi",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "DES": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CAR",
  "size": "Médio",
  "speed": "9 m, escalada 6 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Agilidade Felina (dobra o deslocamento por 1 turno, recarrega ao ficar parado); Garras Felinas (ataque natural e escalada); Talento Felino (proficiência em Percepção e Furtividade)",
  "desc": "Humanoides felinos curiosos e nômades, movidos por histórias e tesouros. Mobilidade explosiva e furtividade — ladinos e monges excelentes.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "cat",
   "head": "feline",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "tritao",
  "name_pt": "Tritão",
  "name_en": "Triton",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "FOR": 1,
   "CON": 1,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+1 FOR, +1 CON, +1 CAR",
  "size": "Médio",
  "speed": "9 m, natação 9 m",
  "darkvision": "—",
  "languages": "Comum, Primordial",
  "traits": "Anfíbio (respira ar e água); Controlar Ar e Água (névoa; rajada de vento no 3º nível; muralha de água no 5º; usa CAR); Emissário do Mar (fala com bestas aquáticas); Guardiões das Profundezas (resistência a frio)",
  "desc": "Nobres protetores dos mares profundos, orgulhosos e cavalheirescos. Anfíbios com magia de controle de elementos — perfeitos para aventuras aquáticas.",
  "appearance": {
   "size": "medium",
   "skin": "#7fb0b0",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "bugbear",
  "name_pt": "Bugbear",
  "name_en": "Bugbear",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "monstruosa",
  "tier_color": "#d08a3a",
  "availability": "Monstruosa — aval do mestre",
  "bonus": {
   "FOR": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 DES",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Goblin",
  "traits": "Membros Longos (alcance +1,5 m em ataques corpo a corpo no turno); Constituição Poderosa; Furtivo (proficiência em Furtividade); Ataque Surpresa (dano extra ao acertar alvo desprevenido no 1º turno)",
  "desc": "Goblinoides grandes e furtivos, predadores de emboscada. Alcance estendido e dano de surpresa brutal — ladinos e guerreiros de ataque pesado.",
  "appearance": {
   "size": "medium",
   "skin": "#7a8a5a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "beast",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "goblin",
  "name_pt": "Goblin",
  "name_en": "Goblin",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "monstruosa",
  "tier_color": "#d08a3a",
  "availability": "Monstruosa — aval do mestre",
  "bonus": {
   "DES": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CON",
  "size": "Pequeno",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Goblin",
  "traits": "Fúria dos Pequenos (dano extra contra criaturas maiores, vezes igual ao bônus de proficiência); Escapada Ágil (Desengajar ou Esconder como ação bônus em cada turno)",
  "desc": "Pequenos e covardes, mas perigosamente espertos em bando. A escapada ágil gratuita os torna ladinos hit-and-run irritantemente eficazes.",
  "appearance": {
   "size": "small",
   "skin": "#7a8a5a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "hobgoblin",
  "name_pt": "Hobgoblin",
  "name_en": "Hobgoblin",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "monstruosa",
  "tier_color": "#d08a3a",
  "availability": "Monstruosa — aval do mestre",
  "bonus": {
   "CON": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Goblin",
  "traits": "Treino Marcial (proficiência com duas armas marciais e armadura leve); Salvar as Aparências (bônus em rolagem após errar, baseado em quantos aliados estão perto)",
  "desc": "Goblinoides militaristas e disciplinados, mestres da tática em grupo. A linhagem mais 'soldado' — guerreiros e magos de batalha organizados.",
  "appearance": {
   "size": "medium",
   "skin": "#7a8a5a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "kobold",
  "name_pt": "Kobold",
  "name_en": "Kobold",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "monstruosa",
  "tier_color": "#d08a3a",
  "availability": "Monstruosa — aval do mestre",
  "bonus": {
   "DES": 2
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES",
  "size": "Pequeno",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Dracônico",
  "traits": "Tática de Bando (vantagem em ataques quando um aliado está adjacente ao alvo); Sensibilidade à Luz Solar (desvantagem em ataques e Percepção visual sob luz solar)",
  "desc": "Pequenos servos dracônicos, fracos sozinhos mas mortais em enxame. Tática de Bando recompensa jogar em grupo coordenado.",
  "appearance": {
   "size": "small",
   "skin": "#6f8f5a",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "reptile",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "orc",
  "name_pt": "Orc",
  "name_en": "Orc",
  "subrace": null,
  "source": "Volo's Guide to Monsters",
  "tier": "monstruosa",
  "tier_color": "#d08a3a",
  "availability": "Monstruosa — aval do mestre",
  "bonus": {
   "FOR": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 CON",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Orc",
  "traits": "Agressivo (ação bônus para mover-se em direção a um inimigo); Ameaçador (proficiência em Intimidação); Constituição Poderosa",
  "desc": "Guerreiros brutais movidos por Gruumsh, feitos para fechar distância rápido. Agressivo os coloca na cara do inimigo no turno 1 — bárbaros ferozes.",
  "appearance": {
   "size": "medium",
   "skin": "#7a8a5a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": "tusks"
  }
 },
 {
  "id": "yuan_ti_sangue_puro",
  "name_pt": "Yuan-ti",
  "name_en": "Yuan-ti Pureblood",
  "subrace": "Sangue-Puro",
  "source": "Volo's Guide to Monsters",
  "tier": "monstruosa",
  "tier_color": "#d08a3a",
  "availability": "Monstruosa — aval do mestre",
  "bonus": {
   "CAR": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CAR, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Abissal, Dracônico",
  "traits": "Conjuração Inata (jato de veneno; amizade animal só com cobras; sugestão no 3º nível; usa CAR); Resistência à Magia (vantagem em saves contra magias e efeitos mágicos); Imunidade a Veneno",
  "desc": "Híbridos serpentinos de cultos antigos, frios e manipuladores. Resistência à magia e imunidade a veneno fazem deles uma das raças mais fortes defensivamente.",
  "appearance": {
   "size": "medium",
   "skin": "#8a9a6a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "reptile",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "githyanki",
  "name_pt": "Githyanki",
  "name_en": "Githyanki",
  "subrace": null,
  "source": "Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "FOR": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Gith, +1 idioma",
  "traits": "Maestria Decadente (proficiência com armadura leve); Prodígio Marcial (proficiência com armaduras leves/médias e armas marciais); Psiônica Githyanki (mão mágica; pulo no 3º nível; passo nebuloso no 5º; usa INT)",
  "desc": "Guerreiros psíquicos do Plano Astral, antigos escravos de illithids. Magia psiônica + treino marcial — guerreiros arcanos formidáveis.",
  "appearance": {
   "size": "medium",
   "skin": "#b6c06a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "githzerai",
  "name_pt": "Githzerai",
  "name_en": "Githzerai",
  "subrace": null,
  "source": "Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "SAB": 2,
   "INT": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 SAB, +1 INT",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Gith, +1 idioma",
  "traits": "Disciplina Mental (vantagem em saves contra encantamento e medo); Psiônica Githzerai (mão mágica; escudo no 3º nível; detectar pensamentos no 5º; usa SAB)",
  "desc": "Monges-filósofos do Limbo, mestres do autocontrole psíquico. Disciplina mental e magia defensiva — monges e místicos serenos.",
  "appearance": {
   "size": "medium",
   "skin": "#c0b48a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "eladrin",
  "name_pt": "Eladrin",
  "name_en": "Eladrin",
  "subrace": null,
  "source": "Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "DES": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CAR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Élfico",
  "traits": "Sentidos Aguçados; Ancestralidade Feérica; Transe; Passo Feérico (teleporte de 9 m como ação bônus, efeito muda conforme a estação escolhida); muda de estação ao descansar",
  "desc": "Elfos do Plano Feérico ligados às estações, de humor cambiante. O teleporte sazonal dá mobilidade e efeitos variados — ótimo para bardos e arcanos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "elfo_marinho",
  "name_pt": "Elfo Marinho",
  "name_en": "Sea Elf",
  "subrace": null,
  "source": "Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "DES": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CON",
  "size": "Médio",
  "speed": "9 m, natação 9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Élfico, Aquático",
  "traits": "Sentidos Aguçados; Ancestralidade Feérica; Transe; Amigo do Mar (comunica com bestas aquáticas); Filho do Mar (respira água, resistência a frio)",
  "desc": "Elfos que escolheram os oceanos, anfíbios e independentes. A raça élfica ideal para campanhas inteiramente subaquáticas.",
  "appearance": {
   "size": "medium",
   "skin": "#7fb0a0",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "shadar_kai",
  "name_pt": "Shadar-kai",
  "name_en": "Shadar-kai",
  "subrace": null,
  "source": "Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "DES": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CON",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Élfico",
  "traits": "Sentidos Aguçados; Ancestralidade Feérica; Transe; Bênção da Rainha Corvo (teleporte de 9 m como ação bônus; após teleportar, resistência a todo dano até o próximo turno; usos por proficiência)",
  "desc": "Elfos sombrios do Shadowfell, servos da Rainha Corvo. O teleporte com resistência a dano os torna duelistas evasivos e mórbidos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "duergar_anao_cinzento",
  "name_pt": "Duergar",
  "name_en": "Duergar",
  "subrace": "Anão Cinzento",
  "source": "Mordenkainen's Tome of Foes",
  "tier": "expansao",
  "tier_color": "#3aa6a0",
  "availability": "Expansão — geralmente liberada",
  "bonus": {
   "CON": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 FOR",
  "size": "Médio",
  "speed": "7,5 m",
  "darkvision": "Visão no Escuro Superior 36 m",
  "languages": "Comum, Anão, Subcomum",
  "traits": "Resiliência Anã; Magia Duergar (aumentar no 3º nível; invisibilidade no 5º; usa INT, só funciona fora da luz solar); Sensibilidade à Luz Solar; Resiliência Psiônica (vantagem em saves contra ilusão, encantamento e paralisia)",
  "desc": "Anões do Subterrâneo, endurecidos pela tirania psíquica. Magia inata e defesas mentais fortes — guerreiros sombrios e resistentes.",
  "appearance": {
   "size": "medium",
   "skin": "#8f8f93",
   "hair": "#b8b2b8",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": true,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "metamorfo",
  "name_pt": "Metamorfo",
  "name_en": "Changeling",
  "subrace": null,
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "CAR": 2
  },
  "bonus_flex": "+2 CAR, +1 em FOR/DES/CON ou INT/SAB à escolha",
  "bonus_text": "+2 CAR, +1 em FOR/DES/CON ou INT/SAB à escolha",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, +2 idiomas",
  "traits": "Metamorfose (muda a aparência como ação, dentro do tamanho médio); Instintos do Metamorfo (proficiência em duas perícias sociais/furtivas à escolha)",
  "desc": "Mudam de forma à vontade — espiões, infiltrados e atores perfeitos. Uma das raças mais versáteis para intriga e disfarce.",
  "appearance": {
   "size": "medium",
   "skin": "#d6ccd2",
   "hair": "#b0a8b8",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "forjado",
  "name_pt": "Forjado",
  "name_en": "Warforged",
  "subrace": null,
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "CON": 2
  },
  "bonus_flex": "+2 CON, +1 em um atributo à escolha",
  "bonus_text": "+2 CON, +1 em um atributo à escolha",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum",
  "traits": "Resiliência Construída (vantagem contra veneno e resistência a dano de veneno; imune a doença; não precisa comer, beber, respirar ou dormir; imune a sono mágico); Descanso de Sentinela (descanso longo permanecendo consciente); Proteção Integrada (+1 CA, pode incorporar armadura); Design Especializado (uma perícia e uma ferramenta)",
  "desc": "Constructos sencientes feitos para a guerra, agora buscando propósito. Imunidades de construto e +1 CA embutida — tanques quase indestrutíveis.",
  "appearance": {
   "size": "medium",
   "skin": "#8a8f99",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "construct",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "kalashtar",
  "name_pt": "Kalashtar",
  "name_en": "Kalashtar",
  "subrace": null,
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "SAB": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 SAB, +1 CAR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Quori, +1 idioma",
  "traits": "Mente Dupla (vantagem em saves de SAB); Disciplina Mental (resistência a dano psíquico); Elo Mental (telepatia com criaturas próximas); Separado dos Sonhos (não dorme nem sonha normalmente, imune a invasão onírica)",
  "desc": "Humanos fundidos a espíritos de sonho de outro plano. Resistência psíquica e telepatia — clérigos, monges e místicos serenos.",
  "appearance": {
   "size": "medium",
   "skin": "#d2b6a0",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "transmorfo_pele_bestial",
  "name_pt": "Transmorfo",
  "name_en": "Shifter",
  "subrace": "Pele-Bestial",
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "CON": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 FOR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum",
  "traits": "Transmorfismo (ação bônus: PV temporários + benefício, 1x por descanso curto/longo); Pele-Bestial concede +1 CA enquanto transformado",
  "desc": "Descendentes de licantropos, despertam traços animais por instantes. A linhagem mais tanque, ganhando armadura natural ao transformar.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "beast",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "transmorfo_presa_longa",
  "name_pt": "Transmorfo",
  "name_en": "Shifter",
  "subrace": "Presa-Longa",
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "FOR": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 DES",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum",
  "traits": "Transmorfismo (PV temporários + ataque de mordida como ação bônus enquanto transformado)",
  "desc": "Shifters de sangue lupino, agressivos e diretos. Ganham uma mordida natural ao se transformar — guerreiros e bárbaros ferozes.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "beast",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "transmorfo_passo_veloz",
  "name_pt": "Transmorfo",
  "name_en": "Shifter",
  "subrace": "Passo-Veloz",
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "DES": 2,
   "CAR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CAR",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum",
  "traits": "Transmorfismo (PV temporários + deslocamento extra e evita ataques de oportunidade enquanto transformado)",
  "desc": "Shifters rápidos e esquivos, de sangue felino. Mobilidade extra ao transformar — ladinos e duelistas evasivos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "beast",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "transmorfo_caca_selvagem",
  "name_pt": "Transmorfo",
  "name_en": "Shifter",
  "subrace": "Caça-Selvagem",
  "source": "Eberron: Rising from the Last War",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Eberron)",
  "bonus": {
   "SAB": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 SAB, +1 DES",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum",
  "traits": "Transmorfismo (PV temporários + vantagem em testes de SAB e ignora vantagem de inimigos contra você enquanto transformado)",
  "desc": "Shifters caçadores de sentidos aguçados. A linhagem mais perceptiva — patrulheiros e druidas rastreadores.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "beast",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "centauro",
  "name_pt": "Centauro",
  "name_en": "Centaur",
  "subrace": null,
  "source": "Guildmasters' Guide to Ravnica",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravnica)",
  "bonus": {
   "FOR": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 SAB",
  "size": "Médio",
  "speed": "12 m",
  "darkvision": "—",
  "languages": "Comum, Silvestre",
  "traits": "Investida (após mover 9 m em linha reta, ataque de cascos como ação bônus com dano extra); Cascos (ataque natural); Corpo Equino (não cabe em alguns espaços, vantagem contra ser empurrado/derrubado); Sobrevivente (proficiência em duas perícias à escolha entre Natureza/Adestrar Animais/Medicina/Sobrevivência)",
  "desc": "Metade humano, metade cavalo, velozes e ligados à natureza. Deslocamento alto e investida — paladinos e patrulheiros de carga pesada.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": "centaur"
  }
 },
 {
  "id": "loxodonte",
  "name_pt": "Loxodonte",
  "name_en": "Loxodon",
  "subrace": null,
  "source": "Guildmasters' Guide to Ravnica",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravnica)",
  "bonus": {
   "CON": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 SAB",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Loxodonte",
  "traits": "Constituição Poderosa; Serenidade do Loxodonte (vantagem contra ser encantado ou amedrontado); Armadura Natural (CA 12+CON, sem armadura); Tromba (manipula objetos, agarra, esguicha água); Olfato Apurado (vantagem em Percepção por cheiro)",
  "desc": "Humanoides-elefante calmos e sábios, de paciência infinita. Armadura natural alta e serenidade mental — clérigos e guardiões estoicos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "elephant",
   "beard": false,
   "halo": false,
   "extra": "trunk"
  }
 },
 {
  "id": "minotauro",
  "name_pt": "Minotauro",
  "name_en": "Minotaur",
  "subrace": null,
  "source": "Guildmasters' Guide / Theros",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Theros)",
  "bonus": {
   "FOR": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 CON",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Minotauro",
  "traits": "Chifres (ataque natural); Investida Cornuda (após mover 3 m, empurra o alvo com a chifrada); Chifres Martelantes (ao acertar com Esbarrão, ataque de chifres como ação bônus); Presença Imponente (proficiência em Intimidação ou Persuasão)",
  "desc": "Touros humanoides poderosos, feitos para empurrar e dominar o campo. Controle de posicionamento com chifres — guerreiros e bárbaros de linha de frente.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "long",
   "wings": "none",
   "tail": "none",
   "head": "bovine",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "hibrido_simic",
  "name_pt": "Híbrido Simic",
  "name_en": "Simic Hybrid",
  "subrace": null,
  "source": "Guildmasters' Guide to Ravnica",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravnica)",
  "bonus": {
   "CON": 2
  },
  "bonus_flex": "+2 CON, +1 em um atributo à escolha",
  "bonus_text": "+2 CON, +1 em um atributo à escolha",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Aprimoramento Animal (escolhe modificações ao longo dos níveis: apêndices de agarrar, natação+respiração aquática, carapaça (+CA), garras de escalada, voo planado etc.)",
  "desc": "Humanoides geneticamente modificados pela guilda Simic, customizáveis. Você 'monta' os traços animais que quiser — uma das raças mais flexíveis mecanicamente.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "vedalken",
  "name_pt": "Vedalken",
  "name_en": "Vedalken",
  "subrace": null,
  "source": "Guildmasters' Guide to Ravnica",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravnica)",
  "bonus": {
   "INT": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 INT, +1 SAB",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Vedalken, +1 idioma",
  "traits": "Imparcialidade Vedalken (vantagem em saves de INT, SAB e CAR); Precisão Incansável (rerrola testes de perícia falhos, vezes por proficiência); Parcialmente Anfíbio (respira água por até 1h)",
  "desc": "Humanoides azuis lógicos e perfeccionistas, mestres do conhecimento. Vantagem em três saves mentais e rerrolagem de perícias — magos e artífices natos.",
  "appearance": {
   "size": "medium",
   "skin": "#7a9ad0",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "leonino",
  "name_pt": "Leonino",
  "name_en": "Leonin",
  "subrace": null,
  "source": "Mythic Odysseys of Theros",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Theros)",
  "bonus": {
   "CON": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CON, +1 FOR",
  "size": "Médio",
  "speed": "10,5 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Leonino",
  "traits": "Garras (ataque natural); Instintos de Caçador (proficiência em duas perícias à escolha entre Atletismo/Intimidação/Percepção/Sobrevivência); Rugido Intimidante (amedronta inimigos próximos como ação bônus, 1x por descanso curto/longo)",
  "desc": "Humanoides-leão orgulhosos e tribais, predadores natos. Garras, velocidade e um rugido que paralisa de medo — bárbaros e guerreiros agressivos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "cat",
   "head": "feline",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "satiro",
  "name_pt": "Sátiro",
  "name_en": "Satyr",
  "subrace": null,
  "source": "Mythic Odysseys of Theros",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Theros)",
  "bonus": {
   "CAR": 2,
   "DES": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 CAR, +1 DES",
  "size": "Médio",
  "speed": "10,5 m",
  "darkvision": "—",
  "languages": "Comum, Silvestre",
  "traits": "Aríete (ataque de chifres); Saltos Alegres (salta distâncias maiores); Festeiro (proficiência em Atuação, Persuasão e um instrumento musical); Resistência à Magia (vantagem em saves contra magias e efeitos mágicos)",
  "desc": "Espíritos feéricos hedonistas, música e travessura em forma de cabra. Resistência à magia + carisma alto — bardos e feiticeiros festeiros.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "short",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": "goat_legs"
  }
 },
 {
  "id": "dhampir",
  "name_pt": "Dhampir",
  "name_en": "Dhampir",
  "subrace": null,
  "source": "Van Richten's Guide to Ravenloft",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravenloft)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "10,5 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Legado Ancestral (mantém traços da raça original); Natureza Imortal (não precisa respirar); Escalar como Aranha (sobe paredes sem testes); Mordida Vampírica (ataque que cura você ou concede bônus, ligado a dados de vida)",
  "desc": "Meio-vampiros que andam entre vivos e mortos, atormentados pela sede. Mordida curativa e escalada de aranha — flexível e sombrio, encaixa em qualquer classe.",
  "appearance": {
   "size": "medium",
   "skin": "#cfc2c6",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "sangue_de_hexa",
  "name_pt": "Sangue de Hexa",
  "name_en": "Hexblood",
  "subrace": null,
  "source": "Van Richten's Guide to Ravenloft",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravenloft)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Legado Ancestral; Símbolo Sinistro (destaca uma parte do corpo para espionar à distância); Magia de Hexa (disfarçar-se e azar/hex); Resiliência Feérica (vantagem contra ser encantado)",
  "desc": "Tocados por bruxas, marcados por pactos sombrios. Magia de maldição inata e truques feéricos — bruxos e feiticeiros de tema gótico.",
  "appearance": {
   "size": "medium",
   "skin": "#cfc2c6",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "renascido",
  "name_pt": "Renascido",
  "name_en": "Reborn",
  "subrace": null,
  "source": "Van Richten's Guide to Ravenloft",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Ravenloft)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Legado Ancestral; Natureza Imortal (não precisa comer, beber nem respirar; vantagem em saves contra veneno e doença); Conhecimento de uma Vida Passada (bônus em testes de perícia, vezes por proficiência)",
  "desc": "Seres que retornaram da morte, com fragmentos de memórias alheias. Imunidades de morto-vivo e flashbacks úteis — personagens misteriosos e ressurretos.",
  "appearance": {
   "size": "medium",
   "skin": "#cfc2c6",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "owlin",
  "name_pt": "Owlin",
  "name_en": "Owlin",
  "subrace": null,
  "source": "Strixhaven: A Curriculum of Chaos",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Strixhaven)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "9 m, voo 9 m",
  "darkvision": "Visão no Escuro 36 m",
  "languages": "Comum, +2 idiomas",
  "traits": "Voo (não pode usar armadura média/pesada para voar); Penas Silenciosas (proficiência em Furtividade); visão no escuro estendida",
  "desc": "Humanoides-coruja noturnos e estudiosos, predadores silenciosos do céu. Voo + furtividade superior — exploradores e arcanos discretos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "feather",
   "tail": "none",
   "head": "avian",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "elfo_astral",
  "name_pt": "Elfo Astral",
  "name_en": "Astral Elf",
  "subrace": null,
  "source": "Spelljammer: Adventures in Space",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Spelljammer)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Ancestralidade Feérica; Transe; Fogo Astral (um truque à escolha entre dança/luz/taumaturgia); Passo Estelar (passo nebuloso, vezes por proficiência); Transe Astral (proficiência em 2 perícias/ferramentas, escolhidas a cada descanso longo)",
  "desc": "Elfos que viveram milênios no Mar Astral, próximos aos deuses. Teleporte recorrente e flexibilidade de perícias — arcanos e exploradores cósmicos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "pointed",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "autognomo",
  "name_pt": "Autognomo",
  "name_en": "Autognome",
  "subrace": null,
  "source": "Spelljammer: Adventures in Space",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Spelljammer)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Pequeno",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Gnômico",
  "traits": "Revestimento Blindado (+1 CA sem armadura); Feito para o Sucesso (bônus em rolagens, vezes por proficiência); Natureza Mecânica (resistência a veneno, imune a doença, não precisa comer/beber/respirar); Descanso de Sentinela; Design Especializado (perícia + ferramenta)",
  "desc": "Pequenos constructos gnômicos sencientes, engenhocas vivas. Imunidades de construto e +1 CA — versão miniatura e versátil do Forjado.",
  "appearance": {
   "size": "small",
   "skin": "#8a8f99",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "construct",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "giff",
  "name_pt": "Giff",
  "name_en": "Giff",
  "subrace": null,
  "source": "Spelljammer: Adventures in Space",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Spelljammer)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, +1 idioma",
  "traits": "Faísca Astral (bônus de dano de força, vezes por proficiência); Maestria com Armas de Fogo (proficiência e ignora propriedade de carregar); Constituição de Hipopótamo (constituição poderosa + vantagem contra ser derrubado)",
  "desc": "Humanoides-hipopótamo militaristas, apaixonados por pólvora. Mestres de armas de fogo e tanques pesados — soldados de fortuna do espaço.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "hadozee",
  "name_pt": "Hadozee",
  "name_en": "Hadozee",
  "subrace": null,
  "source": "Spelljammer: Adventures in Space",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Spelljammer)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, +1 idioma",
  "traits": "Pés Hábeis (usa os pés para tarefas simples); Planar (planeia ao cair, reduzindo dano e movendo-se horizontalmente); Resiliência Hadozee (reduz dano com dados de vida, vezes por proficiência)",
  "desc": "Símios arborícolas adaptados à vida nos cordames das naves. Planeio e mitigação de dano — marinheiros ágeis e acrobáticos do espaço.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "plasmoide",
  "name_pt": "Plasmoide",
  "name_en": "Plasmoid",
  "subrace": null,
  "source": "Spelljammer: Adventures in Space",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Spelljammer)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, +1 idioma",
  "traits": "Amorfo (passa por espaços de 2,5 cm sem se espremer); Prender o Fôlego (até 1h); Resiliência Natural (resistência a ácido e veneno, imune a veneno-condição); Moldar-se (forma pseudópodes, esconde objetos no corpo)",
  "desc": "Massas gelatinosas sencientes que assumem qualquer forma. Resistências e a capacidade de se espremer por frestas — infiltradores alienígenas únicos.",
  "appearance": {
   "size": "medium",
   "skin": "#7fae9a",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": "blob"
  }
 },
 {
  "id": "thri_kreen",
  "name_pt": "Thri-kreen",
  "name_en": "Thri-kreen",
  "subrace": null,
  "source": "Spelljammer: Adventures in Space",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Spelljammer)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Médio ou Pequeno",
  "speed": "9 m",
  "darkvision": "Visão no Escuro 18 m",
  "languages": "Comum, Thri-kreen (telepatia)",
  "traits": "Carapaça Camaleão (+1 CA e vantagem em Furtividade ao ficar imóvel); Braços Secundários (dois braços extras para manipular objetos); Sem Sono (não dorme, medita 4h); Telepatia Thri-kreen",
  "desc": "Mantídeos insectoides de quatro braços, caçadores do deserto e do vácuo. Braços extras, camuflagem e telepatia — guerreiros multitarefa exóticos.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "insect",
   "beard": false,
   "halo": false,
   "extra": "extra_arms"
  }
 },
 {
  "id": "kender",
  "name_pt": "Kender",
  "name_en": "Kender",
  "subrace": null,
  "source": "Dragonlance: Shadow of the Dragon Queen",
  "tier": "cenario",
  "tier_color": "#9b6dff",
  "availability": "De cenário (Dragonlance)",
  "bonus": {},
  "bonus_flex": "+2 e +1 à escolha (flexível)",
  "bonus_text": "+2 e +1 à escolha (flexível)",
  "size": "Pequeno",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, +1 idioma",
  "traits": "Destemido (vantagem em saves contra medo); Talento Kender (proficiência em uma perícia + produz pequenos objetos 'que estavam no bolso'); Provocação (insulto mágico que distrai e penaliza o alvo, vezes por proficiência)",
  "desc": "Pequenos curiosos e destemidos de Krynn, eternas crianças aventureiras. Imunidade a medo e o famoso 'achado de bolso' — ladinos travessos icônicos.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "tortle",
  "name_pt": "Tortle",
  "name_en": "Tortle",
  "subrace": null,
  "source": "The Tortle Package",
  "tier": "avulsa",
  "tier_color": "#8a8597",
  "availability": "Avulsa — suplemento de nicho",
  "bonus": {
   "FOR": 2,
   "SAB": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 FOR, +1 SAB",
  "size": "Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Aquan",
  "traits": "Garras (ataque natural); Prender o Fôlego (até 1h); Armadura Natural (CA 17 fixa, não combina com armadura); Defesa de Casco (recolhe-se no casco: +4 CA, mas incapacitado); Instinto de Sobrevivência (proficiência em Sobrevivência)",
  "desc": "Humanoides-tartaruga pacatos e nômades, com casco como armadura. CA 17 de graça e a defesa de casco — tanques naturais sem precisar de equipamento.",
  "appearance": {
   "size": "medium",
   "skin": "#d8a98c",
   "hair": null,
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "reptile",
   "beard": false,
   "halo": false,
   "extra": "shell"
  }
 },
 {
  "id": "grung",
  "name_pt": "Grung",
  "name_en": "Grung",
  "subrace": null,
  "source": "One Grung Above (Elemental Evil expansão)",
  "tier": "avulsa",
  "tier_color": "#8a8597",
  "availability": "Avulsa — suplemento de nicho",
  "bonus": {
   "DES": 2,
   "CON": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 CON",
  "size": "Pequeno",
  "speed": "7,5 m, escalada 7,5 m",
  "darkvision": "—",
  "languages": "Comum, Grung",
  "traits": "Anfíbio; Pele Venenosa (veneno de contato em quem te atinge desarmado); Imunidade a Veneno; Salto Parado (saltos longos sem corrida); Arborícola (deslocamento de escalada)",
  "desc": "Pequenos sapos venenosos e territoriais das selvas. Veneno de contato e imunidade total a veneno — exóticos e perigosos ao toque (precisam de água doce).",
  "appearance": {
   "size": "small",
   "skin": "#6fae4a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": "blob"
  }
 },
 {
  "id": "locathah",
  "name_pt": "Locathah",
  "name_en": "Locathah",
  "subrace": null,
  "source": "Locathah Rising",
  "tier": "avulsa",
  "tier_color": "#8a8597",
  "availability": "Avulsa — suplemento de nicho",
  "bonus": {
   "DES": 2,
   "FOR": 1
  },
  "bonus_flex": null,
  "bonus_text": "+2 DES, +1 FOR",
  "size": "Médio",
  "speed": "9 m, natação 9 m",
  "darkvision": "—",
  "languages": "Comum, Aquan",
  "traits": "Líder Nato (concede vantagem a um aliado, vezes por proficiência); Armadura Natural (CA 12+DES); Resiliência do Cardume (PV temporários ao receber cura); Sentidos Observadores (proficiência em Percepção); respira água",
  "desc": "Humanoides-peixe resilientes, sobreviventes de tribos dizimadas. Armadura natural e buffs de grupo — guerreiros aquáticos de espírito coletivo.",
  "appearance": {
   "size": "medium",
   "skin": "#7a9a8a",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "avian",
   "beard": false,
   "halo": false,
   "extra": null
  }
 },
 {
  "id": "verdan",
  "name_pt": "Verdan",
  "name_en": "Verdan",
  "subrace": null,
  "source": "Acquisitions Incorporated",
  "tier": "avulsa",
  "tier_color": "#8a8597",
  "availability": "Avulsa — suplemento de nicho",
  "bonus": {
   "CAR": 1,
   "CON": 1,
   "INT": 1
  },
  "bonus_flex": "+1 CAR, +1 CON (e +1 INT ou SAB ao evoluir)",
  "bonus_text": "+1 CAR, +1 CON (e +1 INT ou SAB ao evoluir)",
  "size": "Pequeno ou Médio",
  "speed": "9 m",
  "darkvision": "—",
  "languages": "Comum, Goblin, +1 idioma",
  "traits": "Cura do Sangue Negro (recupera mais PV em descansos); Telepatia Limitada (transmite pensamentos a uma criatura próxima); Persuasivo (proficiência em Persuasão); Percepção Telepática (sente criaturas próximas mesmo sem vê-las)",
  "desc": "Goblinoides em transformação tocados por uma entidade do caos, mutáveis até no tamanho. Cura aprimorada e telepatia — uma raça jovem, estranha e cheia de potencial.",
  "appearance": {
   "size": "small",
   "skin": "#d8a98c",
   "hair": "#3a2f2a",
   "ears": "round",
   "horns": "none",
   "wings": "none",
   "tail": "none",
   "head": "humanoid",
   "beard": false,
   "halo": false,
   "extra": null
  }
 }
];

const TIER_ORDER = ["nucleo","expansao","monstruosa","cenario","avulsa"];
const TIER_LABELS = {nucleo:"Clássicas",expansao:"Comuns",monstruosa:"Exóticas",cenario:"De outros mundos",avulsa:"Raras"};
